import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div className='flex items-center justify-center h-screen'>
			<Head>
				<title>Nextjs + Tailwind CSS + Typescript</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1 className='text-6xl font-bold text-center'>
					Nextjs + Tailwind CSS + Typescript Starter pack
				</h1>
				<p className='mt-10 text-4xl text-center'>
					<a href='https://github.com/moinulmoin/nextjs-tailwind-typescript-starter'>
						⭐ Star this github repo, please :)
					</a>
				</p>
			</main>
		</div>
	);
};

export default Home;
